export const MAIN_HELP = `agentscfg - Unified configuration for AI coding agents

Usage: agentscfg <command> [options]

Commands:
  init        Initialize a new .agentscfg workspace
  validate    Validate workspace structure
  status      Show generation status at a glance
  plan        Show what gen would do without making changes
  diff        Show file diffs for planned changes
  gen         Apply planned changes to target files
  import      Import config from an existing agent setup
  clean       Remove all generated files
  doctor      Diagnose workspace health
  version     Show CLI version

Run 'agentscfg <command> --help' for command-specific help.`;

export const INIT_HELP = `agentscfg init - Initialize a new .agentscfg workspace

Usage: agentscfg init [options]

Options:
  --force    Overwrite existing workspace if present

Creates the .agentscfg directory structure:
  .agentscfg/
    agentscfg.jsonc     # Main configuration
    instructions/
      BASE.md           # Base instructions for all agents
    skills/             # Optional skill definitions

Example:
  agentscfg init
  agentscfg init --force`;

export const VALIDATE_HELP = `agentscfg validate - Validate workspace structure

Usage: agentscfg validate

Checks that:
  - .agentscfg directory exists
  - agentscfg.jsonc is valid JSONC
  - BASE.md exists in instructions/
  - Each skill has a SKILL.md file

Example:
  agentscfg validate`;

export const PLAN_HELP = `agentscfg plan - Show what gen would do without making changes

Usage: agentscfg plan [options]

Options:
  --to <targets>   Comma-separated targets: claude,opencode,codex
                   Default: all enabled targets
  --json           Output plan as JSON

Shows files that would be created, updated, or removed.

Examples:
  agentscfg plan
  agentscfg plan --to claude
  agentscfg plan --to claude,opencode --json`;

export const DIFF_HELP = `agentscfg diff - Show file diffs for planned changes

Usage: agentscfg diff [options]

Options:
  --to <targets>   Comma-separated targets: claude,opencode,codex
                   Default: all enabled targets

Shows unified diffs for all files that would change.

Examples:
  agentscfg diff
  agentscfg diff --to codex`;

export const GEN_HELP = `agentscfg gen - Apply planned changes to target files

Usage: agentscfg gen [options]

Options:
  --to <targets>     Comma-separated targets: claude,opencode,codex
                     Default: all enabled targets
  --remove           Remove orphaned managed files
  --adopt            Adopt unmanaged files that match expected content
  --force            Overwrite unmanaged files (use with caution)
  --allow-dirty      Allow gen even with uncommitted git changes

Safety:
  By default, gen refuses to run if git has uncommitted changes.
  Use --allow-dirty to override (not recommended).

  Files not generated by agentscfg are protected. Use --adopt to
  take ownership of matching files, or --force to overwrite.

Examples:
  agentscfg gen
  agentscfg gen --to claude --allow-dirty
  agentscfg gen --remove --adopt`;

export const DOCTOR_HELP = `agentscfg doctor - Diagnose workspace health

Usage: agentscfg doctor

Checks for:
  - Missing or invalid configuration
  - Orphaned managed files
  - Out-of-sync target files
  - Skill validation issues

Example:
  agentscfg doctor`;

export const IMPORT_HELP = `agentscfg import - Import config from an existing agent setup

Usage: agentscfg import --from <tool>

Options:
  --from <tool>  Source tool: claude, opencode, codex

Imports instructions, skills, targets, and MCP config into .agentscfg/.
Requires an existing .agentscfg/ workspace (run agentscfg init).

Examples:
  agentscfg import --from codex
  agentscfg import --from claude`;

export const STATUS_HELP = `agentscfg status - Show generation status at a glance

Usage: agentscfg status [options]

Options:
  --to <targets>   Comma-separated targets: claude,opencode,codex
                   Default: all enabled targets

Shows which targets are in sync, outdated, or missing.

Legend:
  ✓  In sync (green)
  ○  Outdated (yellow)
  ✗  Missing (red)

Examples:
  agentscfg status
  agentscfg status --to claude`;

export const CLEAN_HELP = `agentscfg clean - Remove all generated files

Usage: agentscfg clean [options]

Options:
  --dry-run    Preview what would be removed without deleting

Removes all files managed by agentscfg:
  - CLAUDE.md, AGENTS.md
  - .claude/, .opencode/, .codex/ directories
  - .mcp.json

Examples:
  agentscfg clean --dry-run
  agentscfg clean`;

export const VERSION_HELP = `agentscfg version - Show CLI version

Usage: agentscfg version

Displays the current version of the agentscfg CLI.

Example:
  agentscfg version`;

export const COMMAND_HELP: Record<string, string> = {
  init: INIT_HELP,
  validate: VALIDATE_HELP,
  status: STATUS_HELP,
  plan: PLAN_HELP,
  diff: DIFF_HELP,
  gen: GEN_HELP,
  import: IMPORT_HELP,
  clean: CLEAN_HELP,
  doctor: DOCTOR_HELP,
  version: VERSION_HELP
};

export const getHelp = (command?: string): string => {
  if (command && command in COMMAND_HELP) {
    return COMMAND_HELP[command]!;
  }
  return MAIN_HELP;
};
