import path from "node:path";
import { Effect } from "effect";
import type { ResolvedAgentCfg } from "../model/config";
import type { InstructionSources } from "../model/workspace";
import { sha256String } from "../../io/hash";

const normalizeLf = (input: string) => input.replace(/\r\n?/g, "\n");

const applyNewlines = (input: string, mode: "lf" | "crlf") =>
  mode === "crlf" ? input.replace(/\n/g, "\r\n") : input;

const ensureTrailingNewline = (input: string) =>
  input.endsWith("\n") ? input : `${input}\n`;

const joinSections = (sections: string[]) => sections.join("\n\n");

const sourceLine = () =>
  "> Source: .agentscfg/instructions/BASE.md (+ PROJECT.md if present)";

const footer = (fileLabel: string, includeProject: boolean, sha: string) =>
  `<!-- agentscfg:generated file=${fileLabel} source=BASE.md${includeProject ? ",PROJECT.md" : ""} sha256=${sha} -->`;

export type InstructionTarget = {
  path: string;
  title: string;
};

export type InstructionOutput = {
  path: string;
  content: string;
  sha: string;
};

export type CompiledInstructions = {
  sha: string;
  includeProject: boolean;
  outputs: InstructionOutput[];
};

export const compileInstructions = (
  cfg: ResolvedAgentCfg,
  instructions: InstructionSources,
  targets: InstructionTarget[]
) =>
  Effect.gen(function* (_) {
    const includeProject =
      cfg.instructions.includeProjectSection &&
      instructions.project !== undefined;
    const baseNormalized = normalizeLf(instructions.base);
    const projectNormalized = includeProject
      ? normalizeLf(instructions.project ?? "")
      : undefined;

    const hashInput =
      baseNormalized + "\n---\n" + (projectNormalized ?? "");
    const sha = yield* _(sha256String(hashInput));

    const baseSection = joinSections(["## Base", baseNormalized]);
    const projectSection = includeProject
      ? joinSections(["## Project", projectNormalized ?? ""])
      : undefined;

    const outputsList: InstructionOutput[] = [];
    for (const target of targets) {
      const title = target.title || "Agent Instructions";
      const fileLabel = path.basename(target.path);
      const body = [
        `# ${title}`,
        "",
        sourceLine(),
        "> Do not edit this file directly; edit the canonical sources instead.",
        "",
        "---",
        "",
        baseSection,
        projectSection ? "" : undefined,
        projectSection,
        "",
        footer(fileLabel, includeProject, sha)
      ]
        .filter((line) => line !== undefined)
        .join("\n");
      const content = applyNewlines(
        ensureTrailingNewline(normalizeLf(body)),
        cfg.output.newlines
      );
      outputsList.push({ path: target.path, content, sha });
    }

    return {
      sha,
      includeProject,
      outputs: outputsList
    } satisfies CompiledInstructions;
  });
