import { Effect } from "effect";
import type { ResolvedAgentCfg } from "../model/config";
import type { InstructionSources } from "../model/workspace";
import { sha256String } from "../../io/hash";

const normalizeLf = (input: string) => input.replace(/\r\n?/g, "\n");

const applyNewlines = (input: string, mode: "lf" | "crlf") =>
  mode === "crlf" ? input.replace(/\n/g, "\r\n") : input;

const ensureTrailingNewline = (input: string) =>
  input.endsWith("\n") ? input : `${input}\n`;

const joinSections = (sections: string[]) => sections.join("\n\n");

const sourceLine = () =>
  "> Source: .agentcfg/instructions/BASE.md (+ PROJECT.md if present)";

const footer = (file: string, includeProject: boolean, sha: string) =>
  `<!-- agentcfg:generated file=${file} source=BASE.md${includeProject ? ",PROJECT.md" : ""} sha256=${sha} -->`;

export type InstructionOutput = {
  path: string;
  content: string;
  sha: string;
};

export type CompiledInstructions = {
  sha: string;
  includeProject: boolean;
  outputs: InstructionOutput[];
};

export const compileInstructions = (
  cfg: ResolvedAgentCfg,
  instructions: InstructionSources,
  outputs: { claude?: string; codex?: string; opencode?: string }
) =>
  Effect.gen(function* (_) {
    const includeProject =
      cfg.instructions.includeProjectSection &&
      instructions.project !== undefined;
    const baseNormalized = normalizeLf(instructions.base);
    const projectNormalized = includeProject
      ? normalizeLf(instructions.project ?? "")
      : undefined;

    const hashInput =
      baseNormalized + "\n---\n" + (projectNormalized ?? "");
    const sha = yield* _(sha256String(hashInput));

    const baseSection = joinSections(["## Base", baseNormalized]);
    const projectSection = includeProject
      ? joinSections(["## Project", projectNormalized ?? ""])
      : undefined;

    const outputsList: InstructionOutput[] = [];

    if (outputs.claude) {
      const body = [
        "# Claude Instructions (Generated by agentcfg)",
        "",
        sourceLine(),
        "> Do not edit this file directly; edit the canonical sources instead.",
        "",
        "---",
        "",
        baseSection,
        projectSection ? "" : undefined,
        projectSection,
        "",
        footer("CLAUDE.md", includeProject, sha)
      ]
        .filter((line) => line !== undefined)
        .join("\n");
      const content = applyNewlines(
        ensureTrailingNewline(normalizeLf(body)),
        cfg.output.newlines
      );
      outputsList.push({ path: outputs.claude, content, sha });
    }

    if (outputs.codex) {
      const body = [
        "# Agent Instructions (Generated by agentcfg)",
        "",
        sourceLine(),
        "> Do not edit this file directly; edit the canonical sources instead.",
        "",
        "---",
        "",
        baseSection,
        projectSection ? "" : undefined,
        projectSection,
        "",
        footer("AGENTS.md", includeProject, sha)
      ]
        .filter((line) => line !== undefined)
        .join("\n");
      const content = applyNewlines(
        ensureTrailingNewline(normalizeLf(body)),
        cfg.output.newlines
      );
      outputsList.push({ path: outputs.codex, content, sha });
    }

    if (outputs.opencode) {
      const body = [
        "---",
        "name: default",
        "purpose: Generated default agent from canonical instructions",
        "---",
        "",
        "# Default Agent (Generated by agentcfg)",
        "",
        "## Base",
        baseNormalized,
        "",
        includeProject ? "## Project" : undefined,
        includeProject ? projectNormalized ?? "" : undefined,
        "",
        footer(".opencode/agent/default.md", includeProject, sha)
      ]
        .filter((line) => line !== undefined)
        .join("\n");
      const content = applyNewlines(
        ensureTrailingNewline(normalizeLf(body)),
        cfg.output.newlines
      );
      outputsList.push({ path: outputs.opencode, content, sha });
    }

    return {
      sha,
      includeProject,
      outputs: outputsList
    } satisfies CompiledInstructions;
  });
